# Generated by Django 3.2.16 on 2023-05-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Q', 'Quotes'), ('P', 'Poems')], max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('ownership', models.IntegerField(choices=[(0, 'My own WordArt'), (1, 'Not my WordArt'), (2, '')], default=2)),
                ('creator', models.CharField(default="Original Author's name", max_length=256)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_post', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='writepost_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=256)),
                ('email', models.EmailField(default='email address', max_length=254)),
                ('comment', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('author_id', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='write.post')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
