# Generated by Django 3.2.16 on 2023-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20230115_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.CharField(default='blank', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='ownership',
            field=models.IntegerField(choices=[(0, 'My own WordArt'), (1, 'Not my WordArt'), (2, '')], default=2),
        ),
    ]
