# Generated by Django 3.2.16 on 2023-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0003_auto_20230115_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.CharField(default="Original Author's name", max_length=256),
        ),
    ]
